### ISSUE TITLE
White theme fonts

### ISSUE THREAD

**Issue by ghost** [ksiazkowicz/lightbulb#59] opened 2014-08-01 13:12 UTC
Fonts are not visible with white theme.

**Comment by ksiazkowicz** [comment] 2014-08-01 14:45
Where?

**Comment by ghost** [comment] 2014-08-02 12:58
![scr_16](https://cloud.githubusercontent.com/assets/5875569/3787945/be5f4c92-1a44-11e4-88d6-9cd161875668.jpg)

**Comment by ksiazkowicz** [comment] 2014-08-02 16:12
Please, next time read the changelog please before posting such stuff :c 
I know it's broken. The whole Events page is broken.

Closing, duplicate of #53, sort of.

**Closed as completed by ksiazkowicz** 2014-08-02 16:12 UTC
Labels: bug, ui
