### ISSUE TITLE
Splashcreen feature , best one (?

### ISSUE THREAD

**Issue by maxicaleca** [ksiazkowicz/lightbulb#32] opened 2014-02-14 00:06 UTC
Hi. I don´t remember if they have posted this request.

I am going to ask you for a feature that is in Whatsapp nowadays. 

a)When you receive a message from one person, the splash shows the name , and the message (on the homescreen ofcourse)

b)If you have the previous message, and one more person wrote to you, then it could says "(2 conversations) "x" new messages. X is the sum of the new messages from both conversations.

This one its worth it :D. Good luck!

 Maximiliano

**Comment by ksiazkowicz** [comment] 2014-02-15 15:05
Duplicate of #12

**Closed as completed by ksiazkowicz** 2014-02-15 15:05 UTC
